"""add team_id to employees

Revision ID: 13f0af66b846
Revises: d0aee427ba36
Create Date: 2026-07-27 10:35:32.284996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13f0af66b846'
down_revision: Union[str, Sequence[str], None] = 'd0aee427ba36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('team_id', sa.Integer(), nullable=True))

    op.create_foreign_key('fk_employees_team_id', 'employees', 'teams', ['team_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_constraint('fk_employees_team_id', 'employees', type_='foreignkey')

    op.drop_column('employees', 'team_id')
    # ### end Alembic commands ###
