from enum import Enum


class InvestigationType(str, Enum):
    PROJECT_DELAY = "PROJECT_DELAY"
    TASK_OVERDUE = "TASK_OVERDUE"
    EMPLOYEE_WORKLOAD = "EMPLOYEE_WORKLOAD"
    WORKFLOW_FAILURE = "WORKFLOW_FAILURE"
    LOW_PRODUCTIVITY = "LOW_PRODUCTIVITY"
    HIGH_COST = "HIGH_COST"
    REVENUE_DROP = "REVENUE_DROP"
    GENERAL = "GENERAL"